### ISSUE TITLE
sending multidimensional in sendNoRetry()

### ISSUE THREAD

**Issue by luishmcmoreno** [lkorth/php-gcm#12]
Why i can send multidimensional array in sendNoRetryMulti and I can't in sendNoRetry? I think you can change the code to send json enconded arrays in sendNoRetry too. If you doesn't have time, maybe, i can do i pull request to you.

Thank you.

**Comment by lkorth** [comment]
Are you trying to pass in an array of `registrationId`s to `Sender#sendNoRetry`? What would be the point of that when you should just use `Sender#sendNoRetryMulti`?

**Comment by luishmcmoreno** [comment]
I'm talking about the payload data, not registrationId. I'm trying to send a data like this:
`
{
    "foo": {
        "bar": "foobar"
    }
}
`
Using sendNoRetryMulti I can, but I can't with sendNoRetry.

**Comment by danielsmithsd** [comment]
Sender::sendNoRetry converts getData to a GET-style query string.  In this process, it blindly iterates over Message::getData and assumes it is a single-dimension array.  This prevents the ability to pass multi-dimensional data through the message.  It appears Google expects to get multi-dimensional data in dot notation when transmitted as form data instead of JSON, e.g., {"foo":{"bar":"foobar"}} would be foo.bar=foobar.

Fixes appear to be 
a) convert Sender::sendNoRetry to use JSON in the request
b) parse getData more thoroughly converting it to dot notation

**Comment by lkorth** [comment]
This was fixed in d459eabeb9d36a8c1e61b58599442f12a4122a7f.
