### ISSUE TITLE
How can I send Big Picture Style notification with this?

### ISSUE THREAD

**Issue by khurshid-alam** [lkorth/php-gcm#28]
How can I send Notification like this?

![big-picture-style-notification](http://i1.wp.com/www.feelzdroid.com/wp-content/uploads/2015/09/expand_notification_android.png?resize=264%2C300)

**Comment by lkorth** [comment]
There is [no direct support](https://firebase.google.com/docs/cloud-messaging/http-server-ref#notification-payload-support) for big picture notifications in GCM or FCM. In order to send a notification that displays a big picture, you will need to send the appropriate data including the url for the picture as a payload using `Message#setData` or `Message#addData` and then process the payload in your application, including downloading the picture if necessary, before displaying the notification.
